version: '3.8'

services:
    app:
        build: ./app
        container_name: key_keeper_api
        env_file:
            - .env
        ports:
            - "8080:8080"
        depends_on:
            - db
        networks:
            - app_network

    ui:
        build: ./ui
        container_name: key_keeper_ui
        ports:
            - "8081:80"
        depends_on:
            - app
        networks:
            - app_network

    db:
        image: postgres:16
        container_name: key_keeper_db
        env_file:
            - .env
        ports:
            - "5434:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - app_network
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "postgres"]
            interval: 5s
            retries: 5

volumes:
    postgres_data:

networks:
    app_network:
